var app = angular.module("myApp",['ngRoute']);
app.run(function($rootScope){
		var data=[
		     {//花王
		     	title:'花王纸尿裤L58片*3，保护宝宝娇嫩屁屁！',
		     	price:275,
		     	delprice:631,
		     	count:2352,
		     	img:'img/11.jpg',
		     	joinday:1055,
		     	category:1001,
		     	pinginfor:"从宝宝出生就用的花王的 ，除了有点小贵，其他都很不错的，好评好评",
		     	pingimg:'img/c.png',
		     	name:'小***爱',
		     	all:600,
		     	logo:'img/23.jpg',
		     	add:'img/22.jpg',
		     	logotitle:'花王极速免税店',
		     	logoadd:"日本直采 保税区发货",
		     	temai:'花王天天特卖',
		     	bao:'单包低至89元',
		     	bigimg:'img/24.jpg',
		     	bigimg1:'img/25.jpg',
		     	bigimg2:'img/26.jpg',
		     	bigimg3:'img/27.jpg',
		     	bigimg4:'img/28.jpg',
		     	bigimg5:'img/29.jpg',
		     	bigimg6:'img/30.jpg',
		     	bigimg7:'img/31.jpg',
		     	bigimg8:'img/32.jpg',
		     	bigimg9:'img/33.jpg',
		     	bigimg10:'img/34.jpg',
		     	bigimg11:'img/35.jpg',
		     	bigimg12:'img/36.jpg',
		     	bigimg13:'img/37.jpg',
		     	bigimg14:'img/38.jpg',
		     	bigimg15:'img/39.jpg',
		     	bigimg16:'img/40.jpg',
		     	bigimg17:'img/41.jpg',
		     	bigimg18:'img/42.jpg',
		     	bigimg19:'img/43.jpg',
		     	bigimg20:'img/44.jpg',
		     	bigimg21:'img/45.jpg',
		     	id:1
		     },
		      {//阿玛尼
		     	title:'阿玛尼小胖丁唇釉，赋予双唇迷情诱惑力！',
		     	price:289,
		     	delprice:340,
		     	count:2668,
		     	id:2,
		     	logo:'img/A1.jpg',
		     	add:'img/A2.jpg',
		     	logotitle:'阿玛尼聚美专卖店',
		     	logoadd:"美丽妆容，始于美丽肌肤",
		     	temai:'我们很倔',
		     	bao:'不打折',
		     	pingimg:'img/q2.jpg',
		     	joinday:2500,
		     	pinginfor:"送女朋友的，女朋友很喜欢",
		     	category:1002,
		     	name:'你***和',
		     	all:26800,
		     	bigimg:'img/A3.jpg',
		     	bigimg1:'img/A4.jpg',
		     	bigimg2:'img/A5.jpg',
		     	bigimg3:'img/A6.jpg',
		     	bigimg4:'img/A7.jpg',
		     	bigimg5:'img/A8.jpg',
		     	bigimg6:'img/A9.jpg',
		     	bigimg7:'img/A10.jpg',
		     	bigimg8:'img/A11.jpg',
		     	bigimg9:'img/A12jpg.jpg',
		     	bigimg10:'img/A13.jpg',
		     	bigimg11:'img/A14.jpg',
		     	bigimg12:'img/A15.jpg',
		     	bigimg13:'img/A16.jpg',
		     	bigimg14:'img/A17.jpg',
		     	bigimg15:'img/A18.jpg',
		     	bigimg16:'img/A19.jpg',
		     	bigimg17:'img/A20.jpg',
		     	bigimg18:'img/A21.jpg',
		     	bigimg19:'img/43.jpg',
		     	bigimg20:'img/44.jpg',
		     	bigimg21:'img/45.jpg',
		     	img:'img/12.jpg'
		     	
		     },
		       {//春雨
		     	title:'春雨 美白保湿蜂胶面膜10片，补水亮白一敷搞定',
		     	price:88,
		     	delprice:180,
		     	count:'1.4万',
		     	id:3,
		     	category:1003,
		     	pingimg:'img/qq1.png',
		     	pinginfor:"好用呢，用完皮肤嫩嫩的 白白的 推荐给大家",
		     	joinday:3056,
		     	name:'艾***够',
		     	all:1890,
		     	logo:'img/CY1.jpg',
		     	add:'img/CY2.jpg',
		     	logotitle:'春雨聚美专卖店',
		     	logoadd:"自然主义的护肤行动派",
		     	temai:'打开美丽世界的大门',
		     	bao:'与你一同变美',
		     	bigimg:'img/CY3.jpg',
		     	bigimg1:'img/CY4.jpg',
		     	bigimg2:'img/CY5.jpg',
		     	bigimg3:'img/CY6.jpg',
		     	bigimg4:'img/CY7.jpg',
		     	bigimg5:'img/CY8.jpg',
		     	bigimg6:'img/CY9.jpg',
		     	bigimg7:'img/CY10.jpg',
		     	bigimg8:'img/CY11.jpg',
		     	bigimg9:'img/CY12.jpg',
		     	bigimg10:'img/CY11.jpg',
		     	bigimg11:'img/CY12.jpg',
		     	bigimg12:'img/CY11.jpg',
		     	bigimg13:'img/CY12.jpg',
		     	bigimg14:'img/CY12.jpg',
		     	bigimg15:'img/CY11.jpg',
		     	bigimg16:'img/CY12.jpg',
		     	bigimg17:'img/CY11.jpg',
		     	bigimg18:'img/CY11.jpg',
		     	bigimg19:'img/43.jpg',
		     	bigimg20:'img/44.jpg',
		     	bigimg21:'img/45.jpg',
		     	img:'img/13.jpg'
		     },
		        {//温碧泉
		     	title:'温碧泉长效保湿三件套，肌肤畅饮水润，缓解干燥服况',
		     	price:99,
		     	delprice:159,
		     	count:'208万',
		     	id:4,
		     	category:1004,
		     	pinginfor:'刚入手，听朋友推荐的，用后再来评价~~',
		     	joinday:2048,
		     	name:'小***票',
		     	pingimg:'img/qq5.png',
		     	all:189,
		     	logo:'img/WBQ1.jpg',
		     	add:'img/WBQ2.jpg',
		     	logotitle:'温碧泉聚官方旗舰店',
		     	logoadd:"补水就用温碧泉",
		     	temai:'想补水',
		     	bao:'交给我',
		     	bigimg:'img/WBQ3.jpg',
		     	bigimg1:'img/WBQ4.jpg',
		     	bigimg2:'img/WBQ5.jpg',
		     	bigimg3:'img/WBQ6.jpg',
		     	bigimg4:'img/WBQ7.jpg',
		     	bigimg5:'img/WBQ8.jpg',
		     	bigimg6:'img/WBQ9.jpg',
		     	bigimg7:'img/WBQ10.jpg',
		     	bigimg8:'img/WBQ11.jpg',
		     	bigimg9:'img/WBQ12.jpg',
		     	bigimg10:'img/WBQ11.jpg',
		     	bigimg11:'img/WBQ12.jpg',
		     	bigimg12:'img/WBQ11.jpg',
		     	bigimg13:'img/WBQ12.jpg',
		     	bigimg14:'img/WBQ12.jpg',
		     	bigimg15:'img/WBQ11.jpg',
		     	bigimg16:'img/WBQ12.jpg',
		     	bigimg17:'img/WBQ11.jpg',
		     	bigimg18:'img/WBQ11.jpg',
		     	bigimg19:'img/43.jpg',
		     	bigimg20:'img/44.jpg',
		     	bigimg21:'img/45.jpg',
		     	img:'img/14.jpg'
		     },
		         {//HT
		     	title:'臻选明星同款 打开新年的别致惊喜',
		     	price:999,
		     	delprice:1780,
		     	count:500,
		     	id:5,
		     	joinday:1059,
		     	category:1005,
		     	all:789,
		     	name:'勇***心',
		     	pinginfor:'跟我女神同款的，表示很满意！！',
		     	pingimg:'img/qq8.png',
		     	logo:'img/15.jpg',
		     	add:'img/DW2.jpg',
		     	logotitle:'DW聚官方旗舰店',
		     	logoadd:"你好瑞典",
		     	temai:'DW瑞典潮流腕表专场',
		     	bao:'全场138元起',
		     	bigimg:'img/DW3.jpg',
		     	bigimg1:'img/DW4.jpg',
		     	bigimg2:'img/DW5.jpg',
		     	bigimg3:'img/DW6.jpg',
		     	bigimg4:'img/DW7.jpg',
		     	bigimg5:'img/DW8.jpg',
		     	bigimg6:'img/DW9.jpg',
		     	bigimg7:'img/DW10.jpg',
		     	bigimg8:'img/DW11.jpg',
		     	bigimg9:'img/DW12.jpg',
		     	bigimg10:'img/DW13.jpg',
		     	bigimg11:'img/DW11.jpg',
		     	bigimg12:'img/DW12.jpg',
		     	bigimg13:'img/DW13.jpg',
		     	bigimg14:'img/DW14.jpg',
		     	bigimg15:'img/DW15.jpg',
		     	bigimg16:'img/DW16.jpg',
		     	bigimg17:'img/DW17.jpg',
		     	bigimg18:'img/DW18.jpg',
		     	bigimg19:'img/43.jpg',
		     	bigimg20:'img/44.jpg',
		     	bigimg21:'img/45.jpg',
		     	img:'img/15.jpg'
		     }
		]
        $rootScope.data=data;
		var pin=[
		     {//咖啡奶茶
		     	title:'咖啡奶茶礼盒600g',
		     	price:37.9,
		     	delprice:100,
		     	img:'img/16.jpg',
		     	id:6,
		     	coffeimg2:'img/coffeimg2.jpg',
		     	coffeimg3:'img/coffeimg3.jpg',
		     	sale:310,
		     	jian:'4罐装礼盒',
		     	jie:'四月茶侬 4罐装咖啡奶茶礼盒600g',
		     	chaping:'img/qq8.png',
		     	chani:'美***吧',
		     	joincha:930,
		     	chapl:'罐头很可爱，开了一袋 味道很不错。一共四种口味，拿铁和卡布奇诺拿去送人了，卖家态度超级好，快递也很给力，总之好评，强推强推！！！',
		     	Allping:500,
		     	logo:'img/cha1.jpg',
		     	logotitle:'四月茶侬旗舰店',
		     	logoadd:'喝茶就找茶侬',
		     	bigimg:'img/CN3.jpg',
		     	bigimg1:'img/CN4.jpg',
		     	bigimg2:'img/CN5.jpg',
		     	bigimg3:'img/CN6.jpg',
		     	bigimg4:'img/CN7.jpg',
		     	bigimg5:'img/CN8.jpg',
		     	bigimg6:'img/CN9.jpg',
		     	bigimg7:'img/CN10.jpg',
		     	bigimg8:'img/CN11.jpg',
		     	bigimg9:'img/CN12.jpg',
		     	bigimg10:'img/CN13.jpg',
		     	bigimg11:'img/CN11.jpg',
		     	bigimg12:'img/CN12.jpg',
		     	bigimg13:'img/CN13.jpg',
		     	bigimg14:'img/CN14.jpg',
		     	bigimg15:'img/CN11.jpg',
		     	bigimg16:'img/CN12.jpg',
		     	bigimg17:'img/CN9.jpg',
		     	bigimg18:'img/CN6.jpg',
		     	bigimg19:'img/43.jpg',
		     	bigimg20:'img/44.jpg',
		     	bigimg21:'img/45.jpg',
		     	only:43.9
		     },
		      {//柠檬片
		     	title:'四川安岳天然冻干柠檬片泡茶50g',
		     	price:13.9,
		     	delprice:68,
		     	img:'img/18.jpg',
		     	id:7,
		     	coffeimg2:'img/NM1.jpg',
		     	coffeimg3:'img/NM2.jpg',
		     	sale:190,
		     	jian:'4罐装礼盒',
		     	jie:'四月茶侬 4罐装咖啡奶茶礼盒600g',
		     	chaping:'img/qq2.jpg',
		     	chani:'你***连',
		     	joincha:503,
		     	chapl:'柠檬片没有菊花那么好喝，每天来一杯，不错的，而且盒子超级实用，很有设计感',
		     	Allping:13500,
		     	logo:'img/cha1.jpg',
		     	logotitle:'四月茶侬旗舰店',
		     	logoadd:'喝茶就找茶侬',
		     	bigimg:'img/NM3.jpg',
		     	bigimg1:'img/NM4.jpg',
		     	bigimg2:'img/NM5.jpg',
		     	bigimg3:'img/NM6.jpg',
		     	bigimg4:'img/NM7.jpg',
		     	bigimg5:'img/NM8.jpg',
		     	bigimg6:'img/NM9.jpg',
		     	bigimg7:'img/NM10.jpg',
		     	bigimg8:'img/NM11.jpg',
		     	bigimg9:'img/NM12.jpg',
		     	bigimg10:'img/NM13.jpg',
		     	bigimg11:'img/NM11.jpg',
		     	bigimg12:'img/NM12.jpg',
		     	bigimg13:'img/NM13.jpg',
		     	bigimg14:'img/NM14.jpg',
		     	bigimg15:'img/NM11.jpg',
		     	bigimg16:'img/NM12.jpg',
		     	bigimg17:'img/NM9.jpg',
		     	bigimg18:'img/NM6.jpg',
		     	bigimg19:'img/43.jpg',
		     	bigimg20:'img/44.jpg',
		     	bigimg21:'img/45.jpg',
		     	only:16.9
		     },
		       {//头饰
		     	title:'韩范淑女气质发圈头饰6件套',
		     	price:8.8,
		     	delprice:180,
		     	count:'1.4万',
		     	id:8,
		     	img:'img/19.jpg',
		     	coffeimg2:'img/QML1.jpg',
		     	coffeimg3:'img/QML2.jpg',
		     	sale:10006,
		     	jian:'给你仙气',
		     	jie:'流苏飘带韩范淑女气质发夹',
		     	chaping:'img/qq5.png',
		     	chani:'米***亿',
		     	joincha:102,
		     	chapl:'朋友们都说很漂亮，不错的购物体验~~ 以后还会光顾的',
		     	Allping:13500,
		     	logo:'img/19.jpg',
		     	logotitle:'奇美拉聚美旗舰店',
		     	logoadd:'你好气质',
		     	bigimg:'img/QML3.jpg',
		     	bigimg1:'img/QML4.jpg',
		     	bigimg2:'img/QML5.jpg',
		     	bigimg3:'img/QML6.jpg',
		     	bigimg4:'img/QML7.jpg',
		     	bigimg5:'img/QML3.jpg',
		     	bigimg6:'img/QML4.jpg',
		     	bigimg7:'img/QML5.jpg',
		     	bigimg8:'img/QML6.jpg',
		     	bigimg9:'img/QML7.jpg',
		     	bigimg10:'img/QML4.jpg',
		     	bigimg11:'img/QML6.jpg',
		     	bigimg12:'img/QML5.jpg',
		     	bigimg13:'img/QML4.jpg',
		     	bigimg14:'img/QML3.jpg',
		     	bigimg15:'img/QML2.jpg',
		     	bigimg16:'img/QML1.jpg',
		     	bigimg17:'img/QML6.jpg',
		     	bigimg18:'img/QML3.jpg',
		     	bigimg19:'img/43.jpg',
		     	bigimg20:'img/44.jpg',
		     	bigimg21:'img/45.jpg',
		     	only:120
		     },
		        {//围巾
		     	title:'冬季仿羊绒保暖针织格纹披肩围巾',
		     	price:99,
		     	delprice:159,
		     	id:9,
		     	count:'208万',
		     	img:'img/20.jpg',
		     	coffeimg2:'img/HT1.jpg',
		     	coffeimg3:'img/HT2.jpg',
		     	sale:10006,
		     	jian:'仿羊绒材质让你过个暖暖的冬天',
		     	jie:'高温定型',
		     	chaping:'img/q4.jpg',
		     	chani:'h***W',
		     	joincha:256,
		     	chapl:'带上暖暖的，样式也是超级棒的。朋友都说好看，，而且超级便宜的，下雪也不怕啦~~',
		     	Allping:13500,
		     	logo:'img/20.jpg',
		     	logotitle:'暖冬聚美旗舰店',
		     	logoadd:'冬天的秘密，帮你守护',
		     	bigimg:'img/WJ3.jpg',
		     	bigimg1:'img/WJ4.jpg',
		     	bigimg2:'img/WJ5.jpg',
		     	bigimg3:'img/WJ6.jpg',
		     	bigimg4:'img/WJ7.jpg',
		     	bigimg5:'img/WJ3.jpg',
		     	bigimg6:'img/WJ4.jpg',
		     	bigimg7:'img/WJ5.jpg',
		     	bigimg8:'img/WJ6.jpg',
		     	bigimg9:'img/WJ7.jpg',
		     	bigimg10:'img/WJ4.jpg',
		     	bigimg11:'img/WJ6.jpg',
		     	bigimg12:'img/WJ5.jpg',
		     	bigimg13:'img/WJ4.jpg',
		     	bigimg14:'img/WJ3.jpg',
		     	bigimg15:'img/WJ2.jpg',
		     	bigimg16:'img/WJ1.jpg',
		     	bigimg17:'img/WJ6.jpg',
		     	bigimg18:'img/WJ3.jpg',
		     	bigimg19:'img/43.jpg',
		     	bigimg20:'img/44.jpg',
		     	bigimg21:'img/45.jpg',
		     	only:130
		     },
		         {//黑糖
		     	title:'黑糖玫瑰姜茶200g*2罐',
		     	price:18.9,
		     	delprice:60,
		     	count:500,
		     	id:10,
		     	img:'img/21.jpg',
		     	coffeimg2:'img/HT1.jpg',
		     	coffeimg3:'img/HT2.jpg',
		     	sale:10006,
		     	jian:'送不锈钢勺',
		     	jie:'黑糖玫瑰姜茶',
		     	chaping:'img/q2.jpg',
		     	chani:'燕***W',
		     	joincha:6636,
		     	chapl:'虽然还没品尝，但看到宝贝以后超级惊喜，包装很高大上，同事都找我要链接呢，还有赠送的小勺子，很精致，不错的体验，大家可以试试~~',
		     	Allping:106,
		     	logo:'img/HT1.jpg',
		     	logotitle:'堂堂聚美旗舰店',
		     	logoadd:'呵护女生呵护你',
		     	bigimg:'img/HT3.jpg',
		     	bigimg1:'img/HT4.jpg',
		     	bigimg2:'img/HT5.jpg',
		     	bigimg3:'img/HT6.jpg',
		     	bigimg4:'img/HT7.jpg',
		     	bigimg5:'img/HT3.jpg',
		     	bigimg6:'img/HT4.jpg',
		     	bigimg7:'img/HT5.jpg',
		     	bigimg8:'img/HT6.jpg',
		     	bigimg9:'img/HT7.jpg',
		     	bigimg10:'img/HT4.jpg',
		     	bigimg11:'img/HT6.jpg',
		     	bigimg12:'img/HT5.jpg',
		     	bigimg13:'img/HT4.jpg',
		     	bigimg14:'img/HT3.jpg',
		     	bigimg15:'img/HT2.jpg',
		     	bigimg16:'img/HT1.jpg',
		     	bigimg17:'img/HT6.jpg',
		     	bigimg18:'img/HT3.jpg',
		     	bigimg19:'img/43.jpg',
		     	bigimg20:'img/44.jpg',
		     	bigimg21:'img/45.jpg',
		     	only:40
		     }
		]
        $rootScope.pin=pin;
        $rootScope.dealClick=function(item){
        	if(item.id==1 || item.id==2 || item.id==3 || item.id==4 || item.id==5){
        		location.href='#/homeDetail/'+item.id
        	}else{
        		location.href='#/pinDetail/'+item.id
        	}					
        }
   })
app.controller("homeController",function ($scope,$rootScope,$http) {
	 clearInterval($rootScope.timer); 
		})
app.controller("pinController",function ($scope,$rootScope,$http) {
	 clearInterval($rootScope.timer); 
		})
app.controller("buycarController",function ($scope,$rootScope,$http,$interval) {
	           clearInterval($rootScope.timer); 
	           var m = 19,
			     s = 59;
			     $rootScope.daojs = m+':'+s;
			     $rootScope.timer=null;
	           $rootScope.timer = $interval(function(){
					s--;
					if (s < 0) {
						s = 59;
						m--;
					}
				    $rootScope.daojs= (m < 10 ? "0" + m : m) + ":" + (s < 10 ? "0" + s : s);
		            if (m <= 0) {
		            	$rootScope.daojs='00:00';
						clearInterval($rootScope.timer);					
					}
	      	
	      },1000)
		}),
app.controller("meController",function ($scope,$rootScope,$http) {
	
		}),
app.controller("homeDetailController",function ($scope,$rootScope,$http,$routeParams,$sce) {
	var id = $routeParams.id;
	if(id==1){
		$rootScope.homeINfor=$rootScope.data[0];
	}else if(id==2){
		$rootScope.homeINfor=$rootScope.data[1];
	}else if(id==3){
		$rootScope.homeINfor=$rootScope.data[2];
	}else if(id==4){
		$rootScope.homeINfor=$rootScope.data[3];
	}else if(id==5){
		$rootScope.homeINfor=$rootScope.data[4];
	}		
})
app.controller("pinDetailController",function ($scope,$rootScope,$http,$routeParams,$sce,$timeout) {
	var id = $routeParams.id;
	if(id==6){
		$rootScope.homeINfor=$rootScope.pin[0];
		console.log($rootScope.homeINfor)
	}else if(id==7){
		$rootScope.homeINfor=$rootScope.pin[1];
	}else if(id==8){
		$rootScope.homeINfor=$rootScope.pin[2];
	}else if(id==9){
		$rootScope.homeINfor=$rootScope.pin[3];
	}else if(id==10){
		$rootScope.homeINfor=$rootScope.pin[4];
	}	
	$timeout(function(){
		var mySwiper = new Swiper(".swiper-container",{
				//自动循环:3000毫秒，切换一次图片
				autoplay: 1000,
				//是否为无缝滚动
				loop: true,
				//指定分页组件
				pagination: ".swiper-pagination",
				//点击小按钮，实现切换图片的效果
				paginationClickable: true,
				//点击后，轮播图继续轮播
				autoplayDisableOnInteraction: false,
			})
	},0.001)
})
app.config(function ($routeProvider){	
				$routeProvider.when("/",{
					controller:"homeController",
					templateUrl:"home.html"
				})
				$routeProvider.when("/home",{
					controller:"homeController",
					templateUrl:"home.html"
				})
				$routeProvider.when("/pin",{
					controller:"pinController",
					templateUrl:"pin.html"
				})
				$routeProvider.when("/buycar",{
					controller:"buycarController",
					templateUrl:"buycar.html"
				})
				$routeProvider.when("/me",{
					controller:"meController",
					templateUrl:"me.html"
				})
				$routeProvider.when("/homeDetail/:id",{
					controller:"homeDetailController",
					templateUrl:"homeDetail.html"
				})
				$routeProvider.when("/pinDetail/:id",{
					controller:"pinDetailController",
					templateUrl:"pinDetail.html"
				})
	})